### ISSUE TITLE
Unable to access the 30 Days of Streamlit app linked in documentation

### ISSUE THREAD

**Issue by sfc-gh-lsaliou** [streamlit/30days-i18n#18]
Here's the error I get when trying to access. 
<img width="980" alt="image" src="https://github.com/user-attachments/assets/cce33db2-28bf-40a0-a706-c81b245a9bd9">

I also get "Domain error. Failed to resolve DNS path for this host" when trying to access https://blog.streamlit.io/30-days-of-streamlit/

**Comment by sfc-gh-kkmiotek** [comment]
@sfc-gh-lsaliou thanks for reporting - the issue has been resolved and the app is working again!
